version: "3.7"
services:
  homebridge:
    build:
      context: .
      dockerfile: docker/homebridge/Dockerfile
    working_dir: /app
    ports:
      - ${HOMEBRIDGE_PORT}:${HOMEBRIDGE_PORT}
    volumes:
      - .:/app
      - ./config.json:/root/.homebridge/config.json

